name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish `onig_sys` crate
      run: (cd onig_sys/ && cargo pubish)
    - name: Pulish `onig` crate
      run: (cd onig/ && cargo publish)
