name: Publish Crates

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Build and Publish Crates
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
          rust-version: stable

    - uses: actions/checkout@master
      with:
          submodules: true
        
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Publish `onig_sys` crate
      run: (cd onig_sys/ && cargo publish --allow-dirty)
      
    - name: Publish `onig` crate
      run: (cd onig/ && cargo publish --allow-dirty)
      env:
        # Add a short delay to ensure the onig_sys crate is available on crates.io
        CARGO_PUBLISH_DELAY: "30"
